### ISSUE TITLE
textDocument/willSaveWaitUntil is a request but implements Notification

### ISSUE THREAD

**Issue by ebkalderon** [gluon-lang/lsp-types#142]
According to the LSP specification, it seems like [`textDocument/willSaveWaitUntil`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_willSaveWaitUntil) is supposed to be a client-to-server request that expects a response back. However, it seems like [`WillSaveWaitUntil`](https://docs.rs/lsp-types/0.71.0/lsp_types/notification/enum.WillSaveWaitUntil.html) implements `Notification` instead and doesn't provide a response type. Is this actually correct?

**Comment by ebkalderon** [comment]
Blocks ebkalderon/tower-lsp#10.

**Comment by Marwes** [comment]
Probably a copy past mistake from the similiarly named https://docs.rs/lsp-types/0.71.0/lsp_types/notification/enum.WillSaveWaitUntil.html. Happy to take a PR!

**Comment by ebkalderon** [comment]
I think you mean https://docs.rs/lsp-types/0.71.0/lsp_types/notification/enum.WillSave.html, which doesn't currently exist. 😂

The spec defines `textDocument/willSave` (notification) and `textDocument/willSaveWaitUntil` (request).

Sure, I'll open up a PR right away!

**Comment by Marwes** [comment]
Copied the wrong url :( https://docs.rs/lsp-types/0.71.0/lsp_types/notification/enum.WillSaveTextDocument.html (it does exist)

**Comment by ebkalderon** [comment]
Yep, sorry! I only just noticed my mistake as well and was just editing my response. I missed it too. 😅

**Comment by ebkalderon** [comment]
Opened pull request #143. Hoping the changes were correct!

**Comment by ebkalderon** [comment]
I also tried my best to keep the ordering consistent with their definition in the upstream spec document, as I've noticed you have done, but please do correct me if I put it in the wrong location.
