### ISSUE TITLE
impl IntoIterator for &'a DocumentSymbol

### ISSUE THREAD

**Issue by runiq** [gluon-lang/lsp-types#162]
Hi,

I'd like to implement `IntoIterator for &'a DocumentSymbol` because [that would simplify displaying the results of `textDocument/documentSymbol`](https://github.com/martskins/LanguageClient-neovim/pull/16) in [my LSP client of choice](https://github.com/autozimu/LanguageClient-neovim).

Would that be a welcome addition?

**Comment by matklad** [comment]
Not sure about this -- `DocumentSymbol` is a tree, and there isn't one obvious way to iterate the tree. Iteration is also not necessary the best interface to consume a tree, as recursion is also a reasonable choice.

Without knowing the details, I'd say it's perhaps better for the client to define their own way of iteration: 

```
fn iter_doc_symbol(symbol: &DocumentSymbol) -> impl Iterator<Item=&DocumentSymbol> + '_
```

**Comment by runiq** [comment]
Oh wow, I've switched over to the builtin client in the meantime. Thanks for the insight, though, much appreciated :)
