### ISSUE TITLE
Adding LSIF types

### ISSUE THREAD

**Issue by HKalbasi** [gluon-lang/lsp-types#214]
LSIF is a JSON format for dumping knowledge of a language server about a code base. It can be used by code viewers to provide ide features without running a language server online.

There is a [dead crate](https://github.com/Xanewok/lsif) that provides LSIF types, and with [minimal changes](https://github.com/hkalbasi/rust-analyzer/blob/master/crates/rust-analyzer/src/cli/lsif/lsif_types.rs) it can be used today. It can live in a seperate crate, but since it depends on `lsp_types` and I think every user of it also depend on `lsp_types` too, for preventing conflicts and for making `lsp_types` and `lsif_types` considering each other in changes, I think it is good to have lsif types inside this repository.

I can file a PR if it is ok to have lsif types inside this repository.

cc https://github.com/rust-analyzer/rust-analyzer/pull/10181

**Comment by Xanewok** [comment]
FWIW I'm more than happy to accept any changes at https://github.com/Xanewok/lsif, I just wasn't developing much using LSIF myself hence why I didn't touch that for a while =)

**Comment by HKalbasi** [comment]
Great! I still think it is better to put lsif types in a module in this crate rather than a separate crate for preventing dependency headaches, at least until [public dependencies](https://github.com/rust-lang/rust/issues/44663) become stabled. But if you don't see benefit in merging these crates, we can continue in the lsif repository.

**Comment by HKalbasi** [comment]
@Xanewok what is your opinion? lsif as a module here or as a seperate repository? I can file a PR if we decide.
