### ISSUE TITLE
`root_uri` in `InitializeParams` should be marked as deprecated

### ISSUE THREAD

**Issue by ematipico** [gluon-lang/lsp-types#247]
The field `rootUri` has been marked as deprecated in the specification: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialize

Although this is not the case for these types. I am not sure which version the crate is following, but I thought that maybe the type should be updated and marked as deprecated too.

If this issue is valid, I am happy to make a PR if that helps.

**Comment by ebkalderon** [comment]
I'm not a maintainer nor a member of this organization, just a recurring contributor: this crate should be _mostly_ following spec version 3.17, minus notebook additions (#229) and document/workspace diagnostics (#258), and perhaps a few other tiny things that were missed. Movement on this project is a bit slow sometimes, sadly.
