### ISSUE TITLE
Bring inlay hints out of "proposal" feature

### ISSUE THREAD

**Issue by kaleidawave** [gluon-lang/lsp-types#251]
Looks like the inlay hints have been standardized of 3.17.0 https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#version_3_17_0

Could these cfg guards now be removed?
https://github.com/gluon-lang/lsp-types/blob/9e6b35372685db1d9dc910964fbea756fbc26966/src/lib.rs#L147-L150

Haven't looked into whether any other guards need to be removed?

**Comment by ebkalderon** [comment]
I've done precisely this in https://github.com/gluon-lang/lsp-types/pull/255 along with other 3.17.0 features.
