### ISSUE TITLE
support inline values?

### ISSUE THREAD

**Issue by OceanBelongsToMe** [gluon-lang/lsp-types#252]

**Comment by Marwes** [comment]
I have no idea what this means. Feel free to reopoen with more context

**Comment by ebkalderon** [comment]
I assume the title refers to the [inline values](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_inlineValue) feature included in LSP 3.17.0. I have included the necessary work to support this in #255.

**Comment by tooltitude-support** [comment]
It looks like the type in this library is different from what's in the spec. The implementation has Option<InlineValue> and the spec has InlineValue[] | null (see the link from the previous comment). Is it possible to change it?

**Comment by Veykril** [comment]
Ye that seems wrong, would be good to open a separate issue about that / a PR fixing it.

**Comment by tooltitude-support** [comment]
@Veykril Sure! Will create a PR shortly.

**Comment by tooltitude-support** [comment]
@Veykril Here it is: https://github.com/gluon-lang/lsp-types/pull/272
