### ISSUE TITLE
Consider not using url crate for directory specifiers?

### ISSUE THREAD

**Issue by dsherret** [gluon-lang/lsp-types#261]
Consider a workspace folder sent from a client that sends a folder url like `"uri": "file:///dev/my-project"` (such as what VSCode does).

https://github.com/gluon-lang/lsp-types/blob/962604a82ba688ad304f8af7aba50010e1414b3a/src/workspace_folders.rs#L26-L31

Given the JSON of that request, this will be deserialize to a `url::Url`. The problem though is the trailing slash is significant to the `Url` crate, so the representation in `Url` is now incorrect because it now considers this a file url rather than a directory. For example, doing `.join` will not work properly (https://docs.rs/url/2.3.1/url/struct.Url.html#method.join -- "Note: a trailing slash is significant."). A consumer of this crate must then take the url out as a string and normalize it to have a trailing slash (then I believe the consumer must also maintain a mapping back to the original unnormalized value when using this in any responses).

Perhaps it would be better if these values were not deserialized to the url crate's `Url` representation?

**Comment by gibbz00** [comment]
[`uriparse-rs`](https://github.com/sgodwincs/uriparse-rs) might be a better alternative. `rust-url` implements https://url.spec.whatwg.org/, not RFC 3986, the latter is the one being used by the [LSP Spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#uri):
> The URI’s format is defined in https://tools.ietf.org/html/rfc3986

**Comment by gibbz00** [comment]
@Marwes 

This should be fixed now that https://github.com/gluon-lang/lsp-types/commit/e3d0ed287e85bc453d7f77a7c9e6d39620b8d1ef exists in master.
