### ISSUE TITLE
Consider #[serde(flatten)] to represent inheritance

### ISSUE THREAD

**Issue by matklad** [gluon-lang/lsp-types#82]
Currently, for example, CompletionParams are represented as

```rust
#[derive(Debug, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CompletionParams {
    // This field was "mixed-in" from TextDocumentPositionParams
    /// The text document.
    pub text_document: TextDocumentIdentifier,

    // This field was "mixed-in" from TextDocumentPositionParams
    /// The position inside the text document.
    pub position: Position,

    // CompletionParams properties:
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context: Option<CompletionContext>,
}
```

What do you think about changing the repr to use composition, like this:

```rust
#[derive(Debug, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CompletionParams {
    #[serde(flatten)]
    pub text_document_position: TextDocumentPositionParams,

    // CompletionParams properties:
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context: Option<CompletionContext>,
}
```

This should make it easier to write code which works both for `TextDocumentPositionParams` and for `CompletionParams`.

For example, I have a generic conversion implemented for TDPP, but it does not work for CP: 

https://github.com/rust-analyzer/rust-analyzer/blob/8d7b8884811dfeed2b18cd334a188df81d33323c/crates/ra_lsp_server/src/conv.rs#L168-L177

**Comment by Marwes** [comment]
👍 Forgot that flatten is implemented now. I have thought about buckling down and implementing it myself for exactly this case but I just never had the bandwidth/priority to do it.
